### ISSUE TITLE
 the weights of ReLoc

### ISSUE THREAD

**Issue by lthcuog** [ZhuangPeiyu/ReLoc#10]
Hello, may I ask you the weights of ReLoc equipped with 3 localization modules (i.e., DFCN, SCSEEUnet, and MVSSNet) trained on DEFACTO dataset. I sent you a friend request on Baidu. Thank you

**Comment by ZhuangPeiyu** [comment]
All the weights are in this link: https://pan.baidu.com/s/1UlQRDXjK6TuhucdOiiyvdQ#list/path=%2F, you can download them with baidu yun.

**Comment by lthcuog** [comment]
Thank you for your reply
I accessed the link you sent, however it redirected to a new page, where it asked me to enter the extraction code to be able to extract the file.
It displays as shown below
![Ảnh chụp màn hình 2024-09-20 235951](https://github.com/user-attachments/assets/6e20efc8-e999-472a-a7e4-67e6f6543619)

**Comment by lthcuog** [comment]
Please grant me permission, and accept me as your friend. I am lethecuong381
![getaddfriendqrcode](https://github.com/user-attachments/assets/3d156c13-55ca-4127-a0a6-12160fc8da01)

**Comment by ZhuangPeiyu** [comment]
This is the code: 
![image](https://github.com/user-attachments/assets/14351dd6-aabe-4120-a96e-1e87fa7969a6)

**Comment by lthcuog** [comment]
Oke , thank you
