### ISSUE TITLE
Will checkpoints be released?

### ISSUE THREAD

**Issue by ghost** [ZhuangPeiyu/ReLoc#3]
First of all thank you for your new idea of ​​image tampering detection, which has new inspiration for me.
For a fairer comparison, I would like to ask if you plan to release checkpoints corresponding to the results reported in the paper, including DFCN, MVSS-Net and SCSEUnet.
Best wishes!

**Comment by ZhuangPeiyu** [comment]
Sure! We will realse the checkpoints as soon as our paper is accepted.
