### ISSUE TITLE
关于test时的F1分数及可视化问题

### ISSUE THREAD

**Issue by Linql7** [ZhuangPeiyu/ReLoc#7]
作者您好，当我使用您提供的权重文件进行test.py时，使用MVSSnet作为loc model时，有可能会出现F1和IOU指标出现为0的效果，但AUC指标正常，如下图所示。
![qweq ](https://github.com/ZhuangPeiyu/ReLoc/assets/98222123/aafc1435-c3fb-45dd-acdf-dd26a2376298)
但使用DenseFCN作为loc model 时检测同一张图片的输出都是正常的，但F1分数可能偏低？如下图
![Snipaste_2024-01-04_13-48-51](https://github.com/ZhuangPeiyu/ReLoc/assets/98222123/40deaf3b-7468-42ec-8b05-11448705ebf9)
如果我想知道具体的可视化检测效果的话，我该怎么做，或者您是否能够提供相应的可视化代码？
非常感谢！

**Comment by Linql7** [comment]
我使用如下代码实现了可视化的结果，但效果并不理想，会出现全黑的mask图，也有检测成功的效果，但仍不是很理想，下图是我的代码设置和检测效果展示。
![1704352452682](https://github.com/ZhuangPeiyu/ReLoc/assets/98222123/f4448081-7334-424c-90b6-236b768b1348)

![1704352000224](https://github.com/ZhuangPeiyu/ReLoc/assets/98222123/d4b60a18-7b05-4164-804d-a48fcc937060)
![1704352293641](https://github.com/ZhuangPeiyu/ReLoc/assets/98222123/5dc56798-63ea-4ee9-94b0-82388345eb12)
请问我的设置是否有误？

**Comment by ZhuangPeiyu** [comment]
这个可视化的代码看起来没啥问题。有时AUC高，F1和IOU小是因为模型对于篡改像素输出的置信度本身就比较低的原因，这个时候0.5的阈值就偏高，导致很多篡改像素被过滤掉了。
