### ISSUE TITLE
有关"Modify the training config of ReLoc in configs.py"步骤的细节

### ISSUE THREAD

**Issue by wrzzzzzzz** [ZhuangPeiyu/ReLoc#8]
作者您好，

注意到训练模型第二步需要做的是修改configs.py文件，想请问具体需要修改的部分是哪里？以及configs_DEFACTO(args)函数中会用到Datasets可以在哪里获得？

谢谢！

**Comment by ZhuangPeiyu** [comment]
修改你自己的训练数据路径

**Comment by wrzzzzzzz** [comment]
好的我来看看，感谢！

**Comment by wrzzzzzzz** [comment]
作者您好，

上一个问题已经解决，还想请问，可否提供公开的训练和测试数据？

非常感谢！

**Comment by ZhuangPeiyu** [comment]
用到的训练和测试数据基本上都是公开的呀，除了那个证书的篡改数据集，那个是当时实验室自建的，目前暂时不会考虑公开。
