### ISSUE TITLE
有关训练问题

### ISSUE THREAD

**Issue by Linql7** [ZhuangPeiyu/ReLoc#9]
作者您好,我最近在尝试复现您的工作,遇到了以下疑问:
1:训练数据集和测试数据集中:按照您的设置Tp图和mask图的文件名必须完全一致,例如Tp/1.jpg,必须对应Gt/1.jpg,但实际上Gt图大多数都为png格式.仅通过更改后缀名是否会影响效果.
2:注意到您设置为image_size为512.这是否意味着您输入模型的所有图片已经预处理大小为512*512,您是否方便分享对于数据预处理的脚本.
感谢您的回复.

**Comment by ZhuangPeiyu** [comment]
1. 你直接修改代码，让图像和mask对应起来就行。不需要去修改文件的后缀名。
2. 是的。我对图像直接使用cv2.resize去进行缩放的，对于mask是用cv2.resize,然后插值方式选择cv2里面的最近邻插值的方式进行缩放的。

**Comment by Linql7** [comment]
非常感谢您的回复，上述问题我已解决。
另外，对于test中的图片进行预测后，如果我想要生成可视化的mask黑白图，请问我该如何进行处理，非常感谢。

**Comment by ZhuangPeiyu** [comment]
选择一个阈值，比如0.5，然后把预测的概率图二值化就行了。
